swagger: "2.0"
info:
  title: Sample Plugin
  version: 0.0.1

definitions:
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string

paths:
  /hello/{subject}:
    get:
      produces:
        - text/plain
      summary: Returns response to greetinge.
      parameters:
        - in: path
          name: subject
          required: true
          type: string
          description: Subject to greet.
      responses:
        200:
          description: returns response greeting
          schema:
            description: tresponse from service
            type: string
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
schemes:
- http

