// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vgryzunov/smart-core/hello-plugin/swagger/models"
)

// GetHelloSubjectOKCode is the HTTP code returned for type GetHelloSubjectOK
const GetHelloSubjectOKCode int = 200

/*GetHelloSubjectOK returns response greeting

swagger:response getHelloSubjectOK
*/
type GetHelloSubjectOK struct {

	/*tresponse from service
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetHelloSubjectOK creates GetHelloSubjectOK with default headers values
func NewGetHelloSubjectOK() *GetHelloSubjectOK {

	return &GetHelloSubjectOK{}
}

// WithPayload adds the payload to the get hello subject o k response
func (o *GetHelloSubjectOK) WithPayload(payload string) *GetHelloSubjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hello subject o k response
func (o *GetHelloSubjectOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHelloSubjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetHelloSubjectDefault error

swagger:response getHelloSubjectDefault
*/
type GetHelloSubjectDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetHelloSubjectDefault creates GetHelloSubjectDefault with default headers values
func NewGetHelloSubjectDefault(code int) *GetHelloSubjectDefault {
	if code <= 0 {
		code = 500
	}

	return &GetHelloSubjectDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get hello subject default response
func (o *GetHelloSubjectDefault) WithStatusCode(code int) *GetHelloSubjectDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get hello subject default response
func (o *GetHelloSubjectDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get hello subject default response
func (o *GetHelloSubjectDefault) WithPayload(payload *models.Error) *GetHelloSubjectDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hello subject default response
func (o *GetHelloSubjectDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHelloSubjectDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
