// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetHelloSubjectParams creates a new GetHelloSubjectParams object
// no default values defined in spec.
func NewGetHelloSubjectParams() GetHelloSubjectParams {

	return GetHelloSubjectParams{}
}

// GetHelloSubjectParams contains all the bound params for the get hello subject operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetHelloSubject
type GetHelloSubjectParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Subject to greet.
	  Required: true
	  In: path
	*/
	Subject string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetHelloSubjectParams() beforehand.
func (o *GetHelloSubjectParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rSubject, rhkSubject, _ := route.Params.GetOK("subject")
	if err := o.bindSubject(rSubject, rhkSubject, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSubject binds and validates parameter Subject from path.
func (o *GetHelloSubjectParams) bindSubject(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Subject = raw

	return nil
}
