// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Sample Plugin",
    "version": "0.0.1"
  },
  "paths": {
    "/hello/{subject}": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "summary": "Returns response to greetinge.",
        "parameters": [
          {
            "type": "string",
            "description": "Subject to greet.",
            "name": "subject",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "returns response greeting",
            "schema": {
              "description": "tresponse from service",
              "type": "string"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Sample Plugin",
    "version": "0.0.1"
  },
  "paths": {
    "/hello/{subject}": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "summary": "Returns response to greetinge.",
        "parameters": [
          {
            "type": "string",
            "description": "Subject to greet.",
            "name": "subject",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "returns response greeting",
            "schema": {
              "description": "tresponse from service",
              "type": "string"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
